# Project Name
TARGET = IBUS_ProtocolParser

# Sources
CPP_SOURCES = IBUS_ProtocolParser.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
