# Project Name
TARGET = Blink

# Sources
CPP_SOURCES = Blink.cpp 

# Library Locations
LIBDAISY_DIR = ../../cores/Arduino
SYSTEM_DIR = ../../system
VARIANT_DIR = ../../variants/STM32H7xx/Dev_DevEBoxH750VB

# Core location, and generic makefile.
include $(LIBDAISY_DIR)/stm32/Makefile

