# Project Name
TARGET = Blink

# Sources
CPP_SOURCES = Blink.cpp 

# Library Locations
LIBDAISY_DIR = ../../cores/Arduino
SYSTEM_DIR = ../../system

# Core location, and generic makefile.
include $(LIBDAISY_DIR)/stm32/Makefile

